spring:
  application:
    name: user
  cloud:
    config:
      uri: ${CONFIG_URI:http://localhost:8888}
      password: ${CONFIG_PASSWORD:connection_security_word}
      username: user
  config:
    import: 'configserver:'
  profiles:
    active: local
  messages:
    basename: error
    encoding: UTF-8
