spring:
  application:
    name: payment
  cloud:
    config:
      uri: ${CONFIG_URI:http://localhost:8083}
      password: ${CONFIG_PASSWORD:connection_security_word}
      username: user
  config:
    import: 'configserver:'
  profiles:
    active: local